name: Add Line on Pull

on:
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  add_line:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Add a new line to the file
      run: echo "New line added on $(date)" >> README.md

    - name: Commit changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add README.md
        git commit -m "Added a new line on pull request"
        git push
